version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: cloud_inventory_postgres
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: cloud_inventory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
